//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int AgendaId { get; set; }
        public string Description { get; set; }
        public System.DateTime AgendaDate { get; set; }
        public string Location { get; set; }
        public string Photo { get; set; }
        public string AgendaTitle { get; set; }
        public System.TimeSpan AgendaStartTime { get; set; }
        public System.TimeSpan AgendaEndTime { get; set; }
        public int EventTypeId { get; set; }
    }
}
