//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEventsContext : DbContext
    {
        public GEventsContext()
            : base("name=GEventsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booths> Booths { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<EventTypes> EventTypes { get; set; }
        public virtual DbSet<FeedBacks> FeedBacks { get; set; }
        public virtual DbSet<Invitations> Invitations { get; set; }
        public virtual DbSet<InvitationSchedules> InvitationSchedules { get; set; }
        public virtual DbSet<InvitationsRefuseds> InvitationsRefuseds { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<SpeakerSchedules> SpeakerSchedules { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Speakers> Speakers { get; set; }
        public virtual DbSet<EventRateSection> EventRateSection { get; set; }
        public virtual DbSet<InvitationsAccepted> InvitationsAccepted { get; set; }
    }
}
