//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEventsContext : DbContext
    {
        public GEventsContext()
            : base("name=GEventsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Speaker> Speakers { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Booth> Booths { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<SpeakerSchedule> SpeakerSchedules { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<InvitationSchedule> InvitationSchedules { get; set; }
        public virtual DbSet<InvitationsRefused> InvitationsRefuseds { get; set; }
    }
}
